"""addition_of_plumbus_model

Revision ID: 01fb45e3e64f
Revises: 06afa7d32b1a
Create Date: 2018-01-09 17:12:10.350620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fb45e3e64f'
down_revision = '06afa7d32b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
