"""Initial database create

Revision ID: 06afa7d32b1a
Revises: 
Create Date: 2018-01-09 16:27:37.893519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06afa7d32b1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chumble',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dinglepop',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleeb',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organic', sa.Boolean(), nullable=True),
    sa.Column('picked_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schleem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('harvested_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schleem')
    op.drop_table('fleeb')
    op.drop_table('dinglepop')
    op.drop_table('chumble')
    # ### end Alembic commands ###
