"""addition_of_plumbus_model

Revision ID: 11f8f4df465f
Revises: 06afa7d32b1a
Create Date: 2018-01-09 17:45:45.706132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f8f4df465f'
down_revision = '06afa7d32b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plumbus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schleem_id', sa.String(), nullable=True),
    sa.Column('dinglepop_id', sa.String(), nullable=True),
    sa.Column('fleeb_id', sa.String(), nullable=True),
    sa.Column('chumble_id', sa.String(), nullable=True),
    sa.Column('manufactured_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chumble_id'], ['chumble.id'], ),
    sa.ForeignKeyConstraint(['dinglepop_id'], ['dinglepop.id'], ),
    sa.ForeignKeyConstraint(['fleeb_id'], ['fleeb.id'], ),
    sa.ForeignKeyConstraint(['schleem_id'], ['schleem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plumbus')
    # ### end Alembic commands ###
