"""addition_of_quote_model

Revision ID: 791497a36aa5
Revises: 06afa7d32b1a
Create Date: 2018-01-09 17:16:21.620249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791497a36aa5'
down_revision = '06afa7d32b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('what', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    # ### end Alembic commands ###
